PartyUp/PartyUp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('partyup/', include('PartyUpApp.urls'), name='index'),
    path('admin/', admin.site.urls)
]

PartyUp/PartyUpApp/urls.py
from email import policy
from django.urls import path,re_path
from . import views

app_name = 'partyupapp'
urlpatterns = [
    path('', views.index, name='home'), # index (initial path)
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('submit/', views.submit, name='submit'),
    path('privacy/', views.policy, name='privacy'),
    path('faq/', views.faq, name='faq'),
    path('create_event/', views.create_event, name='create_event'),
    path('choose_venue/', views.choose_venue, name='choose_venue'),
    path('venue_autocomplete/', views.venue_autocomplete, name='venue_autocomplete'),
    path('vendor_autocomplete/', views.vendor_autocomplete, name='vendor_autocomplete'),
    path('guest_autocomplete/', views.guest_autocomplete, name='guest_autocomplete'),
    path('hire_vendors/', views.choose_vendors, name='choose_vendors'),
    path('invite_guests/', views.invite_guest, name='invite_guests'),
    path('checklist/', views.checklist, name='checklist'),
    path('vendor_info/', views.vendor_info, name='vendor_info'),
    path('guest_info/', views.guest_info, name='guest_info'),
    path('spotify/redirect', views.spotifyCallback, name='spotify_callback'),
    path('spotify/is_authenticated', views.isSpotifyAuthenticated, name='is_spotify_auth'),
    path('spotify/get_auth_url', views.spotifyAuthURL, name='spotify_auth'),
    path('spotify/searchTracks', views.searchTracks, name='search_tracks'),
    path('spotify/searchPlaylist', views.getUserPlaylist, name='search_playlist'),
    path('playlist/', views.playlist, name='playlist'),
    path('user_home/', views.user_home, name='user_home'),
    path('vendor_home/', views.vendor_home, name='vendor_home'),
    path('party_hub/', views.party_hub, name='party_hub'),
    path('logout/', views.logout_view, name='logout'),
    path('event_page/<int:event_id>/', views.event_page, name='event_page'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('payments/', views.payment, name='payment'),
    path('vendor_list/', views.vendor_list, name='vendor_list'),
    path('vendor_profile/', views.vendor_profile, name='vendor_profile'),
    path('vendor_profile/<int:vendor_id>/', views.vendor_profile, name='vendor_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('view_bookings/', views.view_bookings, name='view_bookings'),
    path('payments/finalise', views.finalise, name='finalise_payment'),
    path('event/delete', views.delete_event, name='delete_event')
]

PartyUp/PartyUpApp/models.py
from enum import unique
from pyexpat import model
from tkinter import CASCADE
from django.db import models
from django.db.models import Q,F
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.db.models.functions import Now
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from address.models import AddressField
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


# user model
class User(AbstractUser):
    email = models.EmailField(unique=True)
    display_name = models.CharField(max_length=50)
    is_member = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    phone_number = PhoneNumberField(region='AU', max_length=12)
    REQUIRED_FIELDS = ['email', 'display_name'] 
    # REQUIRED_FIELDS are not the required fields in forms, but the required fields when creating a user
    # via the command line using createsuperuser command

# vendors
class Vendor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField(max_length=160, null=True, blank=True)
    address = AddressField(null=True, blank=True) # Only Vendors of Type Venue should have an address, null=True means that when deleting an AddressField from Vendor, it turns into null, rather than deleting the Vendor themselves
    type = models.CharField(max_length=50)
    price = models.FloatField(null=True) ##add constraint to disallow negative amounts



# party event
class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=160)
    playlist_id = models.CharField(max_length=100,null=True)
    address = AddressField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

# Party checklist item
class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=160, null=True)
    acquired = models.BooleanField(default=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

# Event Guests model
class Guest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'event')

# Payment transaction model
# (for when the users pay the vendors)
class Transaction(models.Model):
    amount = models.FloatField() ##add constraint to disallow negative amounts
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    # Amount paid cannot be <0
    class Meta:
        constraints = [
            models.CheckConstraint(check=Q(amount__gte=0), name= "amount non negative")
        ]
    
    def clean(self):
        if self.amount<0:
            raise ValidationError({'amount':_('amount needs to be non negative.')})

# bookings (between a user and a vendor whose been hired by them)
class Booking(models.Model):
    start_date = models.DateTimeField() ##add constraint and form validation error on past dates 
    end_date = models.DateTimeField() ##add constraint and form validation error on past dates and start_date-end_date >= 15min???
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    vendor_name = models.CharField(max_length=100, blank=True)

    class Meta:
        # end_date > start_date and start_date >= now
        constraints = [
            models.CheckConstraint(check=Q(start_date__lte=F('end_date'),start_date__gte=Now()), name= "correct date_time")
        ]
    
    def clean(self):
        if not (timezone.now() <= self.start_date <= self.end_date):
            raise ValidationError('Invalid start and end datetime')

# This is for using spotify API to create playlists for a party
# You need spotify authentication for this
class SpotifyToken(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    refresh_token = models.CharField(max_length=2000)
    access_token = models.CharField(max_length=2000)
    expires_in = models.DateTimeField()
    token_type = models.CharField(max_length=50)

class Ratings(models.Model):
    rating_user = models.ForeignKey(User, on_delete=models.CASCADE)
    vendor_user = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    rating = models.IntegerField(null=True) ##add constraint and form validation error to check for ranges

    class Meta:
        constraints = [
            models.CheckConstraint(check=(Q(rating__gte=1, rating__lte=5) | Q(rating__isnull=True)), name="rating1-5"),
        ]

    def clean(self):
        if self.rating != None:
            if self.rating > 5 or self.rating < 1:
                raise ValidationError({'rating': _('rating needs to be between 1 and 5 inclusive.')})

PartyUp/PartyUpApp/forms.py
from ast import Add
from cProfile import label
from datetime import datetime

import email

from importlib.metadata import requires
from pyexpat import model
from tracemalloc import start
from urllib import request
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField
from address.forms import AddressField
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.forms import CharField, EmailField, ModelForm, PasswordInput

from PartyUpApp.models import Event, Item, User, Vendor, Ratings

# A member is a normal user
# A vendor is a business partner
account_type_choices = (
    ("Member", "Member"),
    ("Vendor", "Vendor")
)

# A vendor can be any of the following choices
vendor_type_choices = (
    ("Venue", "Venue"),
    ("DJ", "DJ"),
    ("Decorator", "Decorator"),
    ("MC", "MC")
)

# User registration form
class UserSignUpForm(UserCreationForm):
    account_type = forms.ChoiceField(choices=account_type_choices, required=True)
    vendor_type = forms.ChoiceField(choices=vendor_type_choices, required=False)
    number = PhoneNumberField(region='AU', required=True)
    address = AddressField(required=False)

    class Meta:
        model = User
        fields = ["account_type", "vendor_type", "username", "email", "password1", "password2", "number", "address", "display_name"]
        labels = {"account_type": "Register as: ", "vendor_type": "Vendor Type", "password1": "Password", "password2": "Confirm Password", "number": "Mobile Number", "address": "Address", "display_name": "Display Name"}

# Initial party event creating form
class PartyEventInfoForm(forms.ModelForm):
    start_date = forms.DateTimeField(required=True)
    end_date = forms.DateTimeField(required=True)

    class Meta:
        model = Event
        fields = ["name", "description"]
        labels = {"name": "Party Name", "description": "Party Description", "start_date": "Start Time", "end_date": "End Time"}
    
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        if start_date and end_date:
            if not (timezone.now() <= start_date):
                self.add_error('start_date', ValidationError(_('Invalid start date.'), code='invalid'))
            if not (timezone.now() <= end_date):
                self.add_error('end_date', ValidationError(_('Invalid end date.'), code='invalid'))
            if not (start_date <= end_date):
                self.add_error(None, ValidationError(_('End date cannot preceed start date.'), code='invalid'))
            diff = end_date - start_date
            hours = diff.total_seconds() / 60 / 60
            if hours < 1:
                self.add_error(None, ValidationError(_('Party Duration must be at least 1 hour'), code='invalid'))

# Form to choose your own venue when creating events 
# (when you don't want to choose a partnered venue)
class ChooseOwnVenueForm(forms.Form):
    address = AddressField(required=False)

    def clean(self):
        cleaned_data = super().clean()

# Form to choose a partnered venue when creating the event
class ChoosePartneredVenueForm(forms.Form):
    venue_username = forms.CharField(required=False)
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data['venue_username']
        user = User.objects.filter(username=username)
        if len(user) == 1:
            if user[0].is_vendor:
                venue = Vendor.objects.filter(user_id=user[0].id)
                if len(venue) == 1:
                    if venue[0].type == "Venue":
                        return self.cleaned_data
        self.add_error('venue_username', ValidationError(_(f'Venue with username {username} does not exist.'), code='invalid'))


# Form to choose a partnered vendor when creating a party
class ChoosePartneredVendorForm(forms.Form):
    vendor_username = forms.CharField()

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data['vendor_username']

        vendor = Vendor.objects.filter(user__username=username)
        if vendor.exists():
            if len(vendor) == 1:
                if vendor[0].type in ['DJ', 'Decorator', 'MC']:
                    return self.cleaned_data
        self.add_error('vendor_username', ValidationError(_(f'Vendor with username {username} does not exist.'), code='invalid'))

# Form for inviting guests to the party (note that only registered users can get invited)
class InviteGuestsForm(forms.Form):
    # click add button and username gets transferred into the guest list, save the guest list for future when submitting form
    guest_username = forms.CharField()

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data['guest_username']
        user = User.objects.filter(username=username)
        if len(user) == 1:
            if user[0].is_member:
                return username
            raise forms.ValidationError(u'User with username "%s" does not exist.' % username)
        raise forms.ValidationError(u'User with username "%s" does not exist.' % username)

# Form for creating a party checklist
class EnterChecklistForm(forms.ModelForm):
    # have an empty table on the view with empty cell as the first row, enter name and desc and click add 
    # and then progressively add cells the more the user adds items
    class Meta:
        model = Item
        fields = ["name"]
        labels = {"name": "Name"}

# Form to create a party music playlist
class PartyPlaylistForm(forms.Form):
    playlist_name = forms.CharField(max_length=300)
    playlist_search = forms.CharField(max_length=300)
    track_search = forms.CharField(max_length=300)
    track_id = forms.CharField(max_length=300)

# Form to update user details
class UserUpdateForm(ModelForm):
    class Meta:
        model = User 
        fields = ["display_name","email","phone_number"]
        labels = {"display_name":"Display Name","email":"Email","phone_number":"Phone Number"}

# For updating passwords (inherits django's password change form) 
class UserPasswordForm(PasswordChangeForm):
    class Meta:
        model = User 
        

# For updating vendor details (price, description,rating, type)
class VendorUpdateForm(ModelForm):
    class Meta:
        model = Vendor
        fields = ["address","type","description","price"]
        exclude = ['rating']
        labels = {"type":"Type","address":"Address","price":"Price","description":"Description"}

class VendorRatingForm(ModelForm):
    class Meta:
        model = Ratings
        fields = ["vendor_user", "rating"]

PartyUp/PartyUpApp/templates/PartyUpApp/about.html
{% extends "PartyUpApp/base.html" %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/about.css' %}">
{% endblock stylesheets %} 

{% block content %}
<div class="container-fluid col-md-6 about">
  <h class="about-heading"> WHO WE ARE</h>
    <p>
      We are a team of web developers from Sydney, Australia who wants to change the party planning industry. 
      Established in 2022, right after the dark times of lockdowns and social distancing, PartyUp will make sure 
      that you can conviniently plan out your social events and enjoy the freedom of this post-COVID world. 
    </p>
    {% if not user.is_authenticated %}
    <a href="{% url 'partyupapp:register' %}"><button id="try-now" class="btn register-btn">Try PartyUp Now!</button></a>
    {% else %}
    <a href="{% url 'partyupapp:user_home' %}"><button id="try-now" class="btn register-btn">Try PartyUp Now!</button></a>
    {% endif %}
</div>

{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/change_password.html
{% extends "PartyUpApp/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
<script src="{% static 'PartyUpApp/user_profile.js' %}" defer></script>
{% endblock scripts %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/user_profile.css' %}">
{% endblock stylesheets %} 

{% block content %}
<div class="col-xl-8 mx-auto">
    <!-- Account details card-->
    <div class="card" style="padding: 10px;">
        <div class="card-header">Account Details</div>
        <div class="card-body">
            <form method="POST" action="{% url 'partyupapp:change_password' %}">
                {% csrf_token %} 
                <label for="{{ form.old_password.id_for_label }}" class="form-label select-label">{{ form.old_password.label}}</label>
                {{ form.old_password.errors }}
                {% render_field form.old_password class+="form-control" aria-label="Old Password" id="oldPassword" name="old_password"%}
                <label for="{{ form.new_password1.id_for_label }}" class="form-label select-label">{{ form.new_password1.label }}</label>
                {{ form.new_password1.errors }}
                {% render_field form.new_password1 class+="form-control" aria-label="New Password" id="new_password1" name="new_password1"%}
                <label for="{{ form.new_password2.id_for_label }}" class="form-label select-label">{{ form.new_password2.label}}</label>
                {{ form.new_password2.errors }}
                {% render_field form.new_password2 class+="form-control form-input" aria-label="Confirm Password" id="new_password2" name="new_password2"%}
                
                <button type="submit" class="btn btn-primary" style="margin: 0; margin-top: 10px;" id="save-btn">Save</button>
                {% if user.is_vendor %}
                <a href="/partyup/vendor_profile"><button type="button" class="btn btn-danger" style="margin: 0; margin-top: 10px;">Back</button></a>
                {% else %}
                <a href="/partyup/user_profile"><button type="button" class="btn btn-danger" style="margin: 0; margin-top: 10px;">Back</button></a>
                {% endif %}
                {% if messages %}
                <ul class="list-group list-group-flush">
                    {% for message in messages %}
                    <li class="list-group-item">{{ message }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/checklist.html
{% extends "PartyUpApp/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/checklist.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock stylesheets %} 

{% block scripts %}
<script src="{% static 'PartyUpApp/checklist.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<div class="content-element">
    <form id="checklist_form" action="{% url 'partyupapp:spotify_auth' %}" method="GET"> 
        <h2>Party Event Checklist</h2>
        <div class="container">
            <p>Put items in your Party Checklist!</p>
            <p class="form-errors"></p>
            <label for="{{ form.name.id_for_label }}" class="form-label select-label">Name:</label>
            {% render_field form.name class+="form-control" placeholder="Item" aria-label="Item" %}
            <button type="button" class="btn party-add-item-btn">Add</button>
            <span id="item-insertion-error"></span>
            <table id="items_table" class="table">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    
                </tbody>
              </table>

            <div class="submit-wrapper">
                <button type="button" class="btn skip-btn party-venue-btn">Skip Next</button>
                <button type="button" class="btn submit-btn party-venue-btn">Next</button>
            </div>     
        </div>
    </form>
    <form id="skip_checklist_form" action="{% url 'partyupapp:payment' %}" method="GET">
    </form>
</div>
{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/create_event.html
{% extends "PartyUpApp/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/create_event.css' %}">
{% endblock stylesheets %} 

{% block scripts %}
<script src="{% static 'PartyUpApp/create_event.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<div class="content-element">
    <form id="create_event_form" action="{% url 'partyupapp:choose_venue' %}" method="GET"> 
        <p class="form-p">Party Event Creation</p>
        <div class="container">
            <p class="form-errors"></p>
            <label for="{{ form.name.id_for_label }}" class="form-label select-label">{{ form.name.label }}</label>
            <p id="name-error" class="form-field-error"></p>
            {% render_field form.name class+="form-control" placeholder="My Awesome Party" aria-label="Party Name" %}
            
            <label for="{{ form.description.id_for_label }}" class="form-label select-label">{{ form.description.label }}</label>
            <p id="description-error" class="form-field-error"></p>            
            {% render_field form.description class+="form-control" placeholder="Enter description here" aria-label="Party Description" %}

            <div class="date-container container">
                <div class="row">
                    <div class="col-sm">
                        <label for="{{ form.start_date.id_for_label }}" class="form-label select-label">{{ form.start_date.label }}</label>
                        <p id="start-date-error" class="form-field-error" style="display: none;"></p>
                        {% render_field form.start_date class+="form-control" aria-label="Party Start Time" type="datetime-local" %}
                    </div>
                    <div class="col-sm">
                        <label for="{{ form.end_date.id_for_label }}" class="form-label select-label">{{ form.end_date.label }}</label>
                        <p id="end-date-error" class="form-field-error" style="display: none;"></p>
                        {% render_field form.end_date class+="form-control" aria-label="Party End Time" type="datetime-local" %}
                    </div>
                </div>
            </div>
            
            <div class="submit-wrapper">
                <button type="button" class="btn submit-btn party-info-btn">Next</button>
            </div>        
        </div>
    </form>
</div>
{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/hire_vendors.html
{% extends "PartyUpApp/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/hire_vendors.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock stylesheets %} 

{% block scripts %}
<script src="{% static 'PartyUpApp/hire_vendors.js' %}" defer></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
  <script>
    $( function() {
      $( "#id_vendor_username" ).autocomplete({
        source: "{% url 'partyupapp:vendor_autocomplete' %}"
      });
    });
  </script>
{% endblock scripts %}

{% block content %}
<div class="content-element">
    <form id="hire_vendors_form" action="{% url 'partyupapp:invite_guests' %}" method="GET"> 
        <h2>Party Event Hire Vendors</h2>
        <div class="container">
            <p>Hire vendors to elevate your party!</p>
            <p class="form-errors"></p>
            <label for="{{ form.vendor_username.id_for_label }}" class="form-label select-label">Username:</label>
            {% render_field form.vendor_username class+="form-control" placeholder="Username" aria-label="Partnered Vendor Username" %}
            <button type="button" class="btn party-add-vendor-btn">Add</button>
            <span id="vendor-insertion-error"></span>
            <table id="vendor_table" class="table">
                <thead>
                  <tr>
                    <th scope="col">Username</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    
                </tbody>
              </table>

            <div class="submit-wrapper">
                <button type="button" class="btn submit-btn party-venue-btn">Next</button>
            </div>        
        </div>
    </form>

</div>
{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/login.html
{% extends "PartyUpApp/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/login.css' %}">
{% endblock stylesheets %} 

{% block scripts %}
<script src="{% static 'PartyUpApp/login.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<div class="container content-element">
    <form action="{% url 'partyupapp:login' %}" method="POST">
        {% csrf_token %}        
        <div class="container login-container">
            <p class="form-p">Login</p>
            <div class="container form-error">
                {% if form.non_field_errors %}
                    {{form.non_field_errors}}
                {% endif %}
            </div>
            <label for="{{ form.username.id_for_label }}" class="form-label select-label">{{ form.username.label }}</label>
            {% render_field form.username class+="form-control" placeholder="Username" aria-label="Username" %}
            <label for="{{ form.password.id_for_label }}" class="form-label select-label">{{ form.password.label }}</label>
            {% render_field form.password class+="form-control" aria-label="Password" %}
        </div>
        <div class="submit-wrapper">
            <button class="btn register-btn" type="submit">Login</button>
        </div>
    </form>
</div>
{% endblock %}

PartyUp/PartyUpApp/templates/PartyUpApp/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md">
    <div class="container-fluid">
      {% if not user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'partyupapp:home' %}">
      {% else %}
      {% if not user.is_vendor %}
        <a class="navbar-brand" href="{% url 'partyupapp:user_home' %}">
      {% else %}
        <a class="navbar-brand" href="{% url 'partyupapp:vendor_home' %}">
      {% endif %}
      {% endif %}
        <img src="{% static 'PartyUpApp/partyup.png' %}" alt="Party Up Logo">
        <span class="brand-text">PartyUp</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'partyupapp:party_hub' %}">Events</a>
            {% else %}
            <a class="nav-link" href="{% url 'partyupapp:register' %}">Events</a>           
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'partyupapp:vendor_list' %}">Vendors</a>
          </li>
        </ul>
        <ul class="d-flex">
            {% if not user.is_authenticated %}
          <a href="{% url 'partyupapp:login' %}">
            <button class="btn login-btn">Login</button>
          </a>
          <a href="{% url 'partyupapp:register' %}">
            <button class="btn register-btn" type="submit">Register</button>
          </a>
            {% else %}
                <li class="nav-item">
                {% if user.is_vendor %}
                                <a class="nav-link" href="{% url 'partyupapp:vendor_home' %}">{{ user.get_username }}</a>
                    {% else %}
                                <a class="nav-link" href="{% url 'partyupapp:user_home' %}">{{ user.get_username }}</a>
                    {% endif %}

          </li>
          <a href="{% url 'partyupapp:logout' %}">
            <button class="btn login-btn">Logout</button>
          </a>
            {% endif %}

        </ul>
      
      </div>
    </div>
  </nav>

PartyUp/PartyUpApp/templates/PartyUpApp/submit.html
{% extends "PartyUpApp/base.html" %}
{% load static %}

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'PartyUpApp/submit.css' %}">
{% endblock stylesheets %} 

{% block content %}
<div class="row">
    <div class="col-md-6"> 
        <h1 class="heading">
            Message Sent Successfully
        </h1>
        <p class="description">
            Thanks for your message! One of our team members will be in contact shortly.  
        </p>
    </div>
</div>
{% endblock %}